// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockStreamAPI.Models
{
    public partial class Relativo
    {
        public Relativo()
        {
            Agregado = new HashSet<Agregado>();
        }

        public int Id { get; set; }
        public string NomeCompleto { get; set; }
        public string Identificacao { get; set; }
        public string DataNascimento { get; set; }
        public int? UsuarioId { get; set; }
        public string DataCriacao { get; set; }

        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Agregado> Agregado { get; set; }
    }
}