// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockStreamAPI.Models
{
    public partial class Unidade
    {
        public Unidade()
        {
            Produto = new HashSet<Produto>();
        }

        public int Id { get; set; }
        public string Designacao { get; set; }

        public virtual ICollection<Produto> Produto { get; set; }
    }
}