// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockStreamAPI.Models
{
    public partial class Usuario
    {
        public Usuario()
        {
            Agregado = new HashSet<Agregado>();
            Fornecedor = new HashSet<Fornecedor>();
            Fornecimento = new HashSet<Fornecimento>();
            Funcionario = new HashSet<Funcionario>();
            Produto = new HashSet<Produto>();
            Relativo = new HashSet<Relativo>();
        }

        public int Id { get; set; }
        public string Nome { get; set; }
        public string Senha { get; set; }
        public string Token { get; set; }
        public string DataCriacao { get; set; }
        public int? PerfilId { get; set; }
        public int? EstadoLoginId { get; set; }

        public virtual EstadoLogin EstadoLogin { get; set; }
        public virtual Perfil Perfil { get; set; }
        public virtual ICollection<Agregado> Agregado { get; set; }
        public virtual ICollection<Fornecedor> Fornecedor { get; set; }
        public virtual ICollection<Fornecimento> Fornecimento { get; set; }
        public virtual ICollection<Funcionario> Funcionario { get; set; }
        public virtual ICollection<Produto> Produto { get; set; }
        public virtual ICollection<Relativo> Relativo { get; set; }
    }
}