// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace StockStream.Models
{
    public partial class ConsumablesContext : DbContext
    {
        public ConsumablesContext()
        {
        }

        public ConsumablesContext(DbContextOptions<ConsumablesContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Agregado> Agregado { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<CondicaoPagamento> CondicaoPagamento { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<EstadoCivil> EstadoCivil { get; set; }
        public virtual DbSet<EstadoLogin> EstadoLogin { get; set; }
        public virtual DbSet<Fornecedor> Fornecedor { get; set; }
        public virtual DbSet<Fornecimento> Fornecimento { get; set; }
        public virtual DbSet<Funcao> Funcao { get; set; }
        public virtual DbSet<Funcionario> Funcionario { get; set; }
        public virtual DbSet<Genero> Genero { get; set; }
        public virtual DbSet<GrauAcademico> GrauAcademico { get; set; }
        public virtual DbSet<GrauParentesco> GrauParentesco { get; set; }
        public virtual DbSet<Municipio> Municipio { get; set; }
        public virtual DbSet<Nacionalidade> Nacionalidade { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Produto> Produto { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<Relativo> Relativo { get; set; }
        public virtual DbSet<Solicitacao> Solicitacao { get; set; }
        public virtual DbSet<Unidade> Unidade { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Agregado>(entity =>
            {
                entity.Property(e => e.DataCriacao)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.FuncionarioId).HasColumnName("FuncionarioID");

                entity.Property(e => e.GrauParentescoId).HasColumnName("GrauParentescoID");

                entity.Property(e => e.RelativoId).HasColumnName("RelativoID");

                entity.Property(e => e.UsuarioId).HasColumnName("UsuarioID");

                entity.HasOne(d => d.Funcionario)
                    .WithMany(p => p.Agregado)
                    .HasForeignKey(d => d.FuncionarioId)
                    .HasConstraintName("FK__Agregado__Funcio__70DDC3D8");

                entity.HasOne(d => d.GrauParentesco)
                    .WithMany(p => p.Agregado)
                    .HasForeignKey(d => d.GrauParentescoId)
                    .HasConstraintName("FK__Agregado__GrauPa__71D1E811");

                entity.HasOne(d => d.Relativo)
                    .WithMany(p => p.Agregado)
                    .HasForeignKey(d => d.RelativoId)
                    .HasConstraintName("FK__Agregado__Relati__6FE99F9F");

                entity.HasOne(d => d.Usuario)
                    .WithMany(p => p.Agregado)
                    .HasForeignKey(d => d.UsuarioId)
                    .HasConstraintName("FK__Agregado__Usuari__72C60C4A");
            });

            modelBuilder.Entity<Categoria>(entity =>
            {
                entity.Property(e => e.Designacao)
                    .IsRequired()
                    .HasMaxLength(200)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<CondicaoPagamento>(entity =>
            {
                entity.Property(e => e.Designacao)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Departamento>(entity =>
            {
                entity.Property(e => e.Designacao)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<EstadoCivil>(entity =>
            {
                entity.Property(e => e.Designacao)
                    .IsRequired()
                    .HasMaxLength(35)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<EstadoLogin>(entity =>
            {
                entity.Property(e => e.Designacao)
                    .IsRequired()
                    .HasMaxLength(200)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Fornecedor>(entity =>
            {
                entity.Property(e => e.CondicaoPagamentoId).HasColumnName("CondicaoPagamentoID");

                entity.Property(e => e.Contacto1)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Contacto2)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.DataCriacao)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Email)
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.Endereco)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Nif)
                    .HasMaxLength(25)
                    .IsUnicode(false);

                entity.Property(e => e.Nome)
                    .HasMaxLength(70)
                    .IsUnicode(false);

                entity.Property(e => e.UsuarioId).HasColumnName("UsuarioID");

                entity.HasOne(d => d.CondicaoPagamento)
                    .WithMany(p => p.Fornecedor)
                    .HasForeignKey(d => d.CondicaoPagamentoId)
                    .HasConstraintName("FK__Fornecedo__Condi__412EB0B6");

                entity.HasOne(d => d.Usuario)
                    .WithMany(p => p.Fornecedor)
                    .HasForeignKey(d => d.UsuarioId)
                    .HasConstraintName("FK__Fornecedo__Usuar__4222D4EF");
            });

            modelBuilder.Entity<Fornecimento>(entity =>
            {
                entity.Property(e => e.DataCriacao)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.DataFornecimento)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.FornecedorId).HasColumnName("FornecedorID");

                entity.Property(e => e.ProdutoId).HasColumnName("ProdutoID");

                entity.Property(e => e.UsuarioId).HasColumnName("UsuarioID");

                entity.HasOne(d => d.Fornecedor)
                    .WithMany(p => p.Fornecimento)
                    .HasForeignKey(d => d.FornecedorId)
                    .HasConstraintName("FK__Fornecime__Forne__4E88ABD4");

                entity.HasOne(d => d.Produto)
                    .WithMany(p => p.Fornecimento)
                    .HasForeignKey(d => d.ProdutoId)
                    .HasConstraintName("FK__Fornecime__Produ__4D94879B");

                entity.HasOne(d => d.Usuario)
                    .WithMany(p => p.Fornecimento)
                    .HasForeignKey(d => d.UsuarioId)
                    .HasConstraintName("FK__Fornecime__Usuar__4F7CD00D");
            });

            modelBuilder.Entity<Funcao>(entity =>
            {
                entity.Property(e => e.Designacao)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Funcionario>(entity =>
            {
                entity.Property(e => e.Bairro)
                    .HasMaxLength(35)
                    .IsUnicode(false);

                entity.Property(e => e.Casa)
                    .HasMaxLength(15)
                    .IsUnicode(false);

                entity.Property(e => e.ContaBancaria)
                    .HasMaxLength(15)
                    .IsUnicode(false);

                entity.Property(e => e.Contacto1)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Contacto2)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.DataCriacao)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.DataNascimento)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Email)
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.EstadoCivilId).HasColumnName("EstadoCivilID");

                entity.Property(e => e.EstadoLoginId).HasColumnName("EstadoLoginID");

                entity.Property(e => e.GeneroId).HasColumnName("GeneroID");

                entity.Property(e => e.GrauAcademicoId).HasColumnName("GrauAcademicoID");

                entity.Property(e => e.Iban)
                    .HasMaxLength(22)
                    .IsUnicode(false);

                entity.Property(e => e.Identificacao)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.MunicipioId).HasColumnName("MunicipioID");

                entity.Property(e => e.NacionalidadeId).HasColumnName("NacionalidadeID");

                entity.Property(e => e.Nagente)
                    .IsRequired()
                    .HasColumnName("NAgente")
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.NomeCompleto)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Referencia)
                    .HasMaxLength(35)
                    .IsUnicode(false);

                entity.Property(e => e.Rua)
                    .HasMaxLength(35)
                    .IsUnicode(false);

                entity.Property(e => e.Senha)
                    .HasMaxLength(36)
                    .IsUnicode(false);

                entity.Property(e => e.Token)
                    .HasMaxLength(16)
                    .IsUnicode(false);

                entity.Property(e => e.Usuario)
                    .HasMaxLength(36)
                    .IsUnicode(false);

                entity.Property(e => e.UsuarioId).HasColumnName("UsuarioID");

                entity.HasOne(d => d.EstadoCivil)
                    .WithMany(p => p.Funcionario)
                    .HasForeignKey(d => d.EstadoCivilId)
                    .HasConstraintName("FK__Funcionar__Estad__66603565");

                entity.HasOne(d => d.EstadoLogin)
                    .WithMany(p => p.Funcionario)
                    .HasForeignKey(d => d.EstadoLoginId)
                    .HasConstraintName("FK__Funcionar__Estad__6A30C649");

                entity.HasOne(d => d.Genero)
                    .WithMany(p => p.Funcionario)
                    .HasForeignKey(d => d.GeneroId)
                    .HasConstraintName("FK__Funcionar__Gener__68487DD7");

                entity.HasOne(d => d.GrauAcademico)
                    .WithMany(p => p.Funcionario)
                    .HasForeignKey(d => d.GrauAcademicoId)
                    .HasConstraintName("FK__Funcionar__GrauA__6754599E");

                entity.HasOne(d => d.Municipio)
                    .WithMany(p => p.Funcionario)
                    .HasForeignKey(d => d.MunicipioId)
                    .HasConstraintName("FK__Funcionar__Munic__656C112C");

                entity.HasOne(d => d.Nacionalidade)
                    .WithMany(p => p.Funcionario)
                    .HasForeignKey(d => d.NacionalidadeId)
                    .HasConstraintName("FK__Funcionar__Nacio__693CA210");

                entity.HasOne(d => d.UsuarioNavigation)
                    .WithMany(p => p.Funcionario)
                    .HasForeignKey(d => d.UsuarioId)
                    .HasConstraintName("FK__Funcionar__Usuar__6B24EA82");
            });

            modelBuilder.Entity<Genero>(entity =>
            {
                entity.Property(e => e.Designacao)
                    .IsRequired()
                    .HasMaxLength(35)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<GrauAcademico>(entity =>
            {
                entity.Property(e => e.Designacao)
                    .IsRequired()
                    .HasMaxLength(35)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<GrauParentesco>(entity =>
            {
                entity.Property(e => e.Designacao)
                    .IsRequired()
                    .HasMaxLength(40)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Municipio>(entity =>
            {
                entity.Property(e => e.Designacao)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.ProvinciaId).HasColumnName("ProvinciaID");

                entity.HasOne(d => d.Provincia)
                    .WithMany(p => p.Municipio)
                    .HasForeignKey(d => d.ProvinciaId)
                    .HasConstraintName("FK__Municipio__Provi__5441852A");
            });

            modelBuilder.Entity<Nacionalidade>(entity =>
            {
                entity.Property(e => e.Designacao)
                    .IsRequired()
                    .HasMaxLength(200)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Perfil>(entity =>
            {
                entity.Property(e => e.Designacao)
                    .IsRequired()
                    .HasMaxLength(35)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Produto>(entity =>
            {
                entity.Property(e => e.CategoriaId).HasColumnName("CategoriaID");

                entity.Property(e => e.DataCriacao)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.DataFabricacao)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.DataValidade)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Descricao)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Localizacao)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Nome)
                    .HasMaxLength(70)
                    .IsUnicode(false);

                entity.Property(e => e.UnidadeId).HasColumnName("UnidadeID");

                entity.Property(e => e.UsuarioId).HasColumnName("UsuarioID");

                entity.HasOne(d => d.Categoria)
                    .WithMany(p => p.Produto)
                    .HasForeignKey(d => d.CategoriaId)
                    .HasConstraintName("FK__Produto__Categor__48CFD27E");

                entity.HasOne(d => d.Unidade)
                    .WithMany(p => p.Produto)
                    .HasForeignKey(d => d.UnidadeId)
                    .HasConstraintName("FK__Produto__Unidade__49C3F6B7");

                entity.HasOne(d => d.Usuario)
                    .WithMany(p => p.Produto)
                    .HasForeignKey(d => d.UsuarioId)
                    .HasConstraintName("FK__Produto__Usuario__4AB81AF0");
            });

            modelBuilder.Entity<Provincia>(entity =>
            {
                entity.Property(e => e.Designacao)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Relativo>(entity =>
            {
                entity.Property(e => e.DataCriacao)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.DataNascimento)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Identificacao)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.NomeCompleto)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.UsuarioId).HasColumnName("UsuarioID");

                entity.HasOne(d => d.Usuario)
                    .WithMany(p => p.Relativo)
                    .HasForeignKey(d => d.UsuarioId)
                    .HasConstraintName("FK__Relativo__Usuari__628FA481");
            });

            modelBuilder.Entity<Solicitacao>(entity =>
            {
                entity.Property(e => e.DataSolicitacao)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.FuncionarioId).HasColumnName("FuncionarioID");

                entity.Property(e => e.ProdutoId).HasColumnName("ProdutoID");

                entity.HasOne(d => d.Funcionario)
                    .WithMany(p => p.Solicitacao)
                    .HasForeignKey(d => d.FuncionarioId)
                    .HasConstraintName("FK__Solicitac__Funci__75A278F5");

                entity.HasOne(d => d.Produto)
                    .WithMany(p => p.Solicitacao)
                    .HasForeignKey(d => d.ProdutoId)
                    .HasConstraintName("FK__Solicitac__Produ__76969D2E");
            });

            modelBuilder.Entity<Unidade>(entity =>
            {
                entity.Property(e => e.Designacao)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Usuario>(entity =>
            {
                entity.Property(e => e.DataCriacao)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.EstadoLoginId).HasColumnName("EstadoLoginID");

                entity.Property(e => e.Nome)
                    .IsRequired()
                    .HasMaxLength(32)
                    .IsUnicode(false);

                entity.Property(e => e.PerfilId).HasColumnName("PerfilID");

                entity.Property(e => e.Senha)
                    .IsRequired()
                    .HasMaxLength(32)
                    .IsUnicode(false);

                entity.Property(e => e.Token)
                    .HasMaxLength(16)
                    .IsUnicode(false);

                entity.HasOne(d => d.EstadoLogin)
                    .WithMany(p => p.Usuario)
                    .HasForeignKey(d => d.EstadoLoginId)
                    .HasConstraintName("FK__Usuario__EstadoL__3C69FB99");

                entity.HasOne(d => d.Perfil)
                    .WithMany(p => p.Usuario)
                    .HasForeignKey(d => d.PerfilId)
                    .HasConstraintName("FK__Usuario__PerfilI__3B75D760");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}