// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockStream.Models
{
    public partial class Perfil
    {
        public int Id { get; set; }
        public string Designacao { get; set; }
    }
}